### ISSUE TITLE
Support arbitrum with etherscan-api

### ISSUE THREAD

**Issue by alex-image** [sebs/etherscan-api#103]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `etherscan-api@10.0.5` for the project I'm working on.

It would be nice if we could use etherscan-api with Arbiscan out of the box.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/etherscan-api/lib/get-request.js b/node_modules/etherscan-api/lib/get-request.js
index c81c37b..c4e32fd 100644
--- a/node_modules/etherscan-api/lib/get-request.js
+++ b/node_modules/etherscan-api/lib/get-request.js
@@ -18,7 +18,9 @@ const TESTNET_API_URL_MAP = {
   ropsten: 'https://api-ropsten.etherscan.io',
   kovan: 'https://api-kovan.etherscan.io',
   rinkeby: 'https://api-rinkeby.etherscan.io',
-  homestead: 'https://api.etherscan.io'
+  homestead: 'https://api.etherscan.io',
+  arbitrum: 'https://api.arbiscan.io',
+  arbitrumTestnet: 'https://api-testnet.arbiscan.io'
 };
 
 module.exports = function(chain, timeout) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sebs** [comment]
implemented in master will be released soon
