### ISSUE TITLE
Add support for explicit option for livenet

### ISSUE THREAD

**Issue by chevdor** [sebs/etherscan-api#11]
Currently we have:
`require('etherscan-api').init(this.apikey, 'ropsten');` for ropsten
and 
`require('etherscan-api').init(this.apikey);` for mainnet.

It would be nice adding support for:
`require('etherscan-api').init(this.apikey, 'homestead');` for mainnet in order to keep calls similar.

**Comment by sebs** [comment]
7.0.1. should be online soon.

**Comment by sebs** [comment]
implemented as you wished

**Comment by stephenhodgkiss** [comment]
Are you still working on this project? I have just tried to call the balance function and it is returning a different balance than that reported on the Ethereum Mainnet. Please advise. Thanks.
