### ISSUE TITLE
Goerli chain selection fails and uses the mainnet URL

### ISSUE THREAD

**Issue by jonathanmadeley** [sebs/etherscan-api#118]
Goerli network is not available on version 10.2.0 on NPM. 

```
var etherscan = require('etherscan-api');
console.log(etherscan.pickChainUrl("goerli")); >> "api.etherscan.io"
```

This issue has already been resolved in PR: https://github.com/sebs/etherscan-api/pull/113 but no new NPM package is available.

**Comment by sebs** [comment]
closed with 10.2.1
