### ISSUE TITLE
Fetch account balance at a specific block/date

### ISSUE THREAD

**Issue by nitika-goel** [sebs/etherscan-api#19]
Hi,
Is there an API to fetch account balance detail at a specified block or a date. I am working on a project where I need past account balance of an address.
I can see the tool at ethercan but need an API to fetch the same data.
[https://etherscan.io/balancecheck-tool?a=0xc0829421C1d260BD3cB3E0F06cfE2D52db2cE315 
](Tool on etherscan)
Thanks

**Comment by sebs** [comment]
I don't know how to achieve this.

**Comment by nitika-goel** [comment]
@sebs, thanks. Fetched the same using web3.

**Comment by sebs** [comment]
Thanks
