### ISSUE TITLE
weird chain usage in init

### ISSUE THREAD

**Issue by bonesoul** [sebs/etherscan-api#21]
right now i have to use

```
// initialize etherscan api client.
let etherscan = null;
if(config.get('api.etherscan.network') === 'main')
  etherscan = require('etherscan-api').init(config.get('api.etherscan.key'));
else
  etherscan = require('etherscan-api').init(config.get('api.etherscan.key'), config.get('api.etherscan.network'));
```
so if init() accepts an argument of 'mainnet' or so i could simply use;

```
const etherscan = require('etherscan-api').init(config.get('api.etherscan.key'), config.get('api.etherscan.network'));

```

**Comment by m-tymchyk** [comment]
Fixed by commit https://github.com/m-tymchyk/etherscan-api/commit/abfa6f086d7d49a72b5cc559acd15fe0273d265a

And will be in main repository after assert a Pull Request https://github.com/sebs/etherscan-api/pull/20

Try to use an empty value for `api.etherscan.network`. It can help you.

**Comment by bonesoul** [comment]
@m-tymchyk thought that but then my config would be harder to maintain. thanks for the fix.

**Comment by m-tymchyk** [comment]
Pull Request #20 has merged.

**Comment by sebs** [comment]
I will have a look and release soon ;)

**Comment by bonesoul** [comment]
is 'mainnet' option working now? @m-tymchyk

**Comment by m-tymchyk** [comment]
@bonesoul, yes, `mainnet` option working now
