### ISSUE TITLE
Error 'timeout of 3000ms exceeded'

### ISSUE THREAD

**Issue by alexeymarunin** [sebs/etherscan-api#25]
Please, increase axios request timeout in `lib/init.js`

While requesting account.balance for 20 account (see [limitations](https://etherscan.io/apis#accounts) it takes sometimes more 3000ms

**Comment by sebs** [comment]
You can pass a timeout now.  However, I will raise the base timeout, so it would be nice to get an idea how far.

**Comment by sebs** [comment]
I updated the timeout to 10 secs, added docs, and released 8.0.4
