### ISSUE TITLE
If i want query the other token's transaction list, what should i do?

### ISSUE THREAD

**Issue by Sailor20** [sebs/etherscan-api#26]
I use the api.account.txlist query the transaction list, but only find the transaction of eth, if i want query the other token like Erc20 (TCT), what should i do?

thanks for first

**Comment by sebs** [comment]
Uh, I probably can not answer you this. Maybe turn to the official etherscan service to ask this question. If there is an api missing: I can add it. 
You have to find the example for yourself though
