### ISSUE TITLE
typescript types

### ISSUE THREAD

**Issue by moodysalem** [sebs/etherscan-api#27]
this package would be dope with typescript types

**Comment by sebs** [comment]
Throw me an example ;)

**Comment by moodysalem** [comment]
there's a lot of examples of typescript definition packages here
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types

however, i think the easiest way to do this is to port to the code to typescript (and you'll probably catch a few bugs while you're at it.) this my favorite starter. it handles semantic version and bundling and doc generation properly already
https://github.com/alexjoverm/typescript-library-starter

is that what you mean?

**Comment by sebs** [comment]
ah thanks for the info. I wont type the result in any way. I will improve parameter handling however. Thank you for the import.
