### ISSUE TITLE
question: rate limiting?

### ISSUE THREAD

**Issue by kasperfish** [sebs/etherscan-api#28]
does this module incorporate the rate limits for calling the etherscan api (max 5/s)?

**Comment by sebs** [comment]
No it does not, should I  and how if so? 
No problem to add a feature here

**Comment by kasperfish** [comment]
well I already did some rate limiting myself by making my script synchronous.
https://github.com/eosdac/conversion/tree/master/fallback

**Comment by sebs** [comment]
So you just wanna mak e sure, the client is not overstepping a limit ;) Ahh I c ;) I will tinker about this, ok?

**Comment by sebs** [comment]
https://www.npmjs.com/package/bottleneck

**Comment by sebs** [comment]
This would be my goto solution
