### ISSUE TITLE
how to use eth_call ?

### ISSUE THREAD

**Issue by xbhuang1994** [sebs/etherscan-api#30]
`var eth_call =  api.proxy.eth_call("0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413","getBuyPrice","");

eth_call.then(function(data1){
  console.log(data1);
}).catch((err)=>{
  console.log(JSON.stringify(err.message));
})`

I don't quite understand how to use it correctly?

**Comment by sebs** [comment]
this is the original docs of the call made in web3, which should be the api you are accessing here https://web3py.readthedocs.io/en/latest/web3.eth.html#web3.eth.Eth.call
