### ISSUE TITLE
The client returns incorrect gas price

### ISSUE THREAD

**Issue by slavafomin** [sebs/etherscan-api#36]
Hello!

Thank you for this great library!

However, for some reason, the client returns the gas price different from calling the API directly.

If I open: `https://api.etherscan.io/api?module=proxy&action=eth_gasPrice` in browser the response would be `0xff2eb0d0`, which is `4281250000 wei`. However, when I do the request using the client: `client.proxy.eth_gasPrice()`, I'm always getting the same result: `0x3b9aca00`, which is `1000000000 wei`.

This leads to incorrect gas price calculated for our transactions. What could be causing this?

Thanks!

**Comment by sebs** [comment]
Uh that is concerning. Let me check that out. Thank you for the report.

**Comment by slavafomin** [comment]
@sebs sure. Let me know if I can help.

**Comment by slavafomin** [comment]
@sebs wait a moment. It looks like we are using severely outdated package (`3.0.11`). Let me upgrade and check this out again.

**Comment by slavafomin** [comment]
Sorry for the false alarm. I accidentally was using it in `rinkeby` network and not in `mainnet`. That's why the results were different.

**Comment by sebs** [comment]
ez ;) ty and have a nice day.
