### ISSUE TITLE
Promise returned was never settled

### ISSUE THREAD

**Issue by slavafomin** [sebs/etherscan-api#41]
Hello!

Thank you for this useful module!

However, we have had an incident recently. I was hoping you could help us to understand what could have caused it.

We were using `"etherscan-api": "^8.1.5"` and calling `proxy.eth_blockNumber()` method. However, for some reason, the promise returned from the method was never settled (resolved or rejected), which blocked execution of our calling function.

I can see that you are passing a `timeout` of 10 seconds to `axios` by default (and we were not changing it). So it shouldn't be the problem. However, do you have tests for the timeout case?

Also, do you have any ideas what could have caused it? Any suggestions will be highly appreciated.

Thank you!

@sebs @m-tymchyk

**Comment by slavafomin** [comment]
Have you had similar issues (reports) with this library before? Could it be the problem with `axios` itself?

**Comment by sebs** [comment]
I'd say its and unhandled error from the . method on etherscan. Let me see if I can look into in. Etherscan aint the most "normalized" api, so I would not wonder to find something. Let me give it a look. 

No, I don't think its a problem with axios itself.  But you know .. sure and bug in one sentence.m However: I will throw some time on it.

**Comment by sebs** [comment]
Just try the latest version please ;)

**Comment by sebs** [comment]
Had a look into it, you are not stating which network you are using - can you please get me that info. The proxy methods are a bit different from the rest of the codebase from etherscan. They are a api access to a real web3 node. 

The call is rather standard and should be easy to reproduce and there is a test for it - yes I was surprised ;)

**Comment by slavafomin** [comment]
Thank you @sebs for looking into it!
The problem occurred with the main Ethereum network.

What do you think if we add an additional layer of timeout protection around all API calls? Just to be on a safe side. I can create a PR for this, the changes should be minimal. And this will help to catch these kind of errors in production and to verify that it actually happens somewhere down there.

**Comment by sebs** [comment]
See #43

**Comment by sebs** [comment]
> Thank you @sebs for looking into it!
> The problem occurred with the main Ethereum network.
> 
> What do you think if we add an additional layer of timeout protection around all API calls? Just to be on a safe side. I can create a PR for this, the changes should be minimal. And this will help to catch these kind of errors in production and to verify that it actually happens somewhere down there.

I will close this issue, feel free to provide a sane timout bugfix, keep it small, adhere to the style ;) I will have a look and I am happy to merge it ;)
