### ISSUE TITLE
Library throws error on empty txlist response

### ISSUE THREAD

**Issue by slavafomin** [sebs/etherscan-api#42]
Hello again!

After updating to the latest version of the library I've started to experience some weird issue with the `account.txlist` request. When Etherscan API returns empty result, the library treats it as an incorrect response and throws the rejected promise with the cryptic `"NOTOK"` message.

That's where it happens:
https://github.com/sebs/etherscan-api/blob/master/lib/get-request.js#L39-L45

Also, it's incorrect to pass a string as a rejection argument. It should be `new Error(returnMessage)` instead.

The core problem though is that error message is not passed correctly, it should be: `reject(new Error(data.message))` in this case.

Here's the value of such a response:

```
{
  "status": "0",
  "message": "No transactions found",
  "result": []
}
```

**Comment by slavafomin** [comment]
I'm not very familiar with Etherscan API response format, but my guess would be that each section of the API (or a group of sections) have different response format (which leads to an issues like this).

My suggestion would be to actually pass the `module` and `action` variables to the `getRequest` function and to handle the response parsing according to the module/action.

Please, consider the following example:

```js
function getRequest(query, module, action) {

  return client.get('/api?' + query)
    .then(response => {

      const data = response.data;

      switch (module) {

        case 'account':

          /**
          {
            "status": "0",
            "message": "No transactions found",
            "result": []
          }
          */

          if (0 === data.status) {
            return Promise.reject(new Error(data.message));
          } else {
            return data.result;
          }

        default:

          // ... default (common) handling logic

          return data;

      }

    })
    // Probably this catch is not required at all
    .catch(error => {
      if (error instanceof Error) {
        reject(error); // passing as is
      } else {
        reject(new Error(error)); // wrapping in error
      }
    })
  ;

}
```

It's not a final implementation, but a very much close to it. Also, notice that this function could be simplified. No need to call `new Promise()` because axios already returns a promise.

**Comment by sebs** [comment]
Hold your horses with a PR -..... 

I guess I will write some swagger definition and re-release the mod as a open api export. This will take some time, but it will tackle the issue of apis giving different responses in a well defined way. + focus is on testing the code and not writing boiler plate stuff.

**Comment by sebs** [comment]
I guess we have to do #43

**Comment by sebs** [comment]
can I close this? ;) Not sure atm. If not, there is time to improve more
