### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by sebs** [sebs/etherscan-api#43]
There are some issues to the codebase that make further development more heavy lifitng than I want it to be. I wanted to take time to outline further developments in this ticket. 

## Not a es6 codebase 

The whole codebase is banking on node js and I would like it to be usable in a browser as well. best case no transpiling of any sort.  In any case all code shall be pure es6 and use  fetch for requests

## hand crafted code

The whole code around the api is hand crafted and this research result in the docs were no clearly documented in a document but directly put into the codebase. This backfires now. It needs to be fixed with a machine readable definition of the API  first. Swagger comes into mind and this homework has to be done. This way the requests can be generated from the definition and we can easier handle different response and error codes. 

## integration tests where unit tests are needed

We have a bunch of integration tests on the api, but these are very slow and needlesly shaky. 

# What is next? 

1. Definition of a swagger API description 
2. Adding first fixtures from the etherscan server to allow for local unit testing. 
3. Creating a client from the spec
4. transpiling node js code from the es6 code
5. Running test suites with teh created clients

Profit!

If you are willing to help or contribute! ;) Please do so .. I will open a branch soon

**Comment by maikelmclauflin** [comment]
@sebs i'd be down to help. do you have issues to work on? also, would you be interested in gprc? cross language api may be useful to alleviate some of the burden

**Comment by sebs** [comment]
Yes, we might start out with editing a swagger file. Ill be happily accepting a PR containing one of these for etherscan. Why not start here?
