### ISSUE TITLE
Service Unavailable: Back-end server is at capacity

### ISSUE THREAD

**Issue by Manidos** [sebs/etherscan-api#6]
Hey! I'm not sure if this is the right place to file this issue, but I'm doing it anyway, because you probably know where to redirect this to.
Anyway, I've got these two errors in browser console (30 minutes ago everything worked just fine)

> XMLHttpRequest cannot load https://api.etherscan.io/api?module=stats&action=ethprice&apikey=W26RIS92HKQWJHCMXTRRJT4SSRX2P1K8F5. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 503

> GET https://api.etherscan.io/api?module=stats&action=ethprice&apikey=W26RIS92HKQWJHCMXTRRJT4SSRX2P1K8F5 503 (Service Unavailable: Back-end server is at capacity)

**Comment by Manidos** [comment]
It's back to normal again

**Comment by sebs** [comment]
As for the first one: You seem to be using the lib in a brwoser context. See [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for that
