### ISSUE TITLE
get calls periodically hang

### ISSUE THREAD

**Issue by mateodelnorte** [sebs/etherscan-api#7]
periodically, get calls like `account.balance(x)` hang. because of the way the library is written, there is no way to pass timeout parameters to the calls, and there appear to be no timeout settings provided by default. 

is there a way to set a default timeout, such that an error is thrown upon timeout?

**Comment by sebs** [comment]
ah 
;) 
Features: just make a wish. I probably was a very lazy boy doing this and I am happy to correct my fails ;) Any code examples etc will speed up the process.

**Comment by sebs** [comment]
Ah now i see it. I will put some changes and you can pass your own options to the restify client. I must experiment with this a bit.

**Comment by sebs** [comment]
8.0.1. has a timeout parameter. I suspect this will not solve the hangs. 

Can be improved by complete axios params, other ways of calling it, maybe via async. However all this requires another major change so I close this ticket now. Thanks for playing the game. Sorry for late reply
