### ISSUE TITLE
Gett list of transactions by address

### ISSUE THREAD

**Issue by memo** [sebs/etherscan-api#76]
Hi, thanks for this great library. I was wondering if you've implemented get "Get list of transactions by address" functionality? I couldn't see it in the docs. (Interestingly, as far as I can tell this isn't possible with web3, so the etherscanapi is needed for it).

Cheers,

From:
https://etherscan.io/apis#accounts

Get a list of 'Normal' Transactions By Address

[Optional Parameters] startblock: starting blockNo to retrieve results, endblock: ending blockNo to retrieve results

https://api.etherscan.io/api?module=account&action=txlist&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a&startblock=0&endblock=99999999&sort=asc&apikey=YourApiKeyToken

(Returned 'isError' values: 0=No Error, 1=Got Error)

(Returns up to a maximum of the last 10000 transactions only)

or

https://api.etherscan.io/api?module=account&action=txlist&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a&startblock=0&endblock=99999999&page=1&offset=10&sort=asc&apikey=YourApiKeyToken

(To get paginated results use page=<page number> and offset=<max records to return>)

Get a list of 'Internal' Transactions by Address

[Optional Parameters] startblock: starting blockNo to retrieve results, endblock: ending blockNo to retrieve results

https://api.etherscan.io/api?module=account&action=txlistinternal&address=0x2c1ba59d6f58433fb1eaee7d20b26ed83bda51a3&startblock=0&endblock=2702578&sort=asc&apikey=YourApiKeyToken

(Returned 'isError' values: 0=No Error, 1=Got Error)

(Returns up to a maximum of the last 10000 transactions only)

or

https://api.etherscan.io/api?module=account&action=txlistinternal&address=0x2c1ba59d6f58433fb1eaee7d20b26ed83bda51a3&startblock=0&endblock=2702578&page=1&offset=10&sort=asc&apikey=YourApiKeyToken

(To get paginated results use page=<page number> and offset=<max records to return>)

Get "Internal Transactions" by Transaction Hash

https://api.etherscan.io/api?module=account&action=txlistinternal&txhash=0x40eb908387324f2b575b4879cd9d7188f69c8fc9d87c901b9e2daaea4b442170&apikey=YourApiKeyToken

(Returned 'isError' values: 0=Ok, 1=Rejected/Cancelled)

(Returns up to a maximum of the last 10000 transactions only)

**Comment by bkr32** [comment]
@memo were you able to find a substitute for this? or just used etherscan's API as is?

**Comment by memo** [comment]
I ended up using a combination of etherscan API as is, and web3js (i can't remember which one for this exact thing)
