### ISSUE TITLE
[Enhancement] Hope to support customized httpsagent config for axios

### ISSUE THREAD

**Issue by AtlasQuan** [sebs/etherscan-api#83]
I believe working behind a corporate proxy is a common scenario. And suggested by this blog, https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d, I hope to have an option to customize the httpsproxy for axios request when using the etherscan-api.

Hope it makes sense.

Thanks.

**Comment by dansejijie** [comment]
> I believe working behind a corporate proxy is a common scenario. And suggested by this blog, https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d, I hope to have an option to customize the httpsproxy for axios request when using the etherscan-api.
> 
> Hope it makes sense.
> 
> Thanks.

i agree

**Comment by sebs** [comment]
ill jump n it asap

**Comment by sebs** [comment]
you can now pass a own instance of axios in init ... see readme 

Release 10.2.0 is implementing this and published.
